[package]
name = "tennis_matrix"
version = "0.1.0"
authors = ["donkerevader <ctweeduizendvier@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
